dial_needle_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: dial_needle
    joint_speed: 0.5
    motor:
        id: 14
        init: 512
        min: 0
        max: 1023
